name: CI

on:
  push:
    branches: [master, rewatch-lsp]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run compile
      - run: bun run bundle
      - run: make checkformat

      - name: Store short commit SHA for filename
        id: vars
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: echo "sha_short=${COMMIT_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Package Extension
        run: bunx vsce package --no-yarn -o rescript-vscode-${{ steps.vars.outputs.sha_short }}.vsix

      - uses: actions/upload-artifact@v4
        with:
          name: rescript-vscode-${{ steps.vars.outputs.sha_short }}.vsix
          path: rescript-vscode-${{ steps.vars.outputs.sha_short }}.vsix
